language: java
addons:
  mariadb: '10.0'
jdk:
  - oraclejdk8
before_script:
  - mysql -e "use mysql; update user set password=PASSWORD('123456') where User='root'; flush privileges;" -uroot
  - mysql -uroot -p123456 < testsql/unielwin_course.sql
  - mysql -uroot -p123456 < testsql/unielwin_prof.sql
  - mysql -uroot -p123456 < testsql/unielwin_RA.sql
  - mysql -uroot -p123456 < testsql/unielwin_registration.sql
  - mysql -uroot -p123456 < testsql/unielwin_student.sql
  - mysql -uroot -p123456 < testsql/Mutagenesis_std_Atom.sql
  - mysql -uroot -p123456 < testsql/Mutagenesis_std_bond.sql
  - mysql -uroot -p123456 < testsql/Mutagenesis_std_Mole.sql
  - mysql -uroot -p123456 < testsql/Mutagenesis_std_moleatm.sql
script: 
  - cd jar
  - java -jar RunBB.jar
  - ls
  - cd ../src
  - javac -cp ".:./lib/*" Config.java BZScriptRunner.java MakeSetup.java
  - javac -cp ".:./lib/*" RunBB.java
  - javac -cp ".:./lib/*" MakeTargetSetup.java
  - javac -cp ".:./lib/*" FunctorWrapper.java
  - mv *.class ../
  - cd ..
  - java -cp ".:./src/lib/*" MakeSetup
  - java -cp ".:./src/lib/*" RunBB
  - java -cp ".:./src/lib/*" MakeTargetSetup
  - java -cp ".:./src/lib/*" FunctorWrapper
  - ls
after_script:
  - mysql -e "show databases;" -uroot -p123456
