language: java
services:
  - mysql
jdk:
  - oraclejdk8
before_script:
  - mysql -e "use mysql; update user set password=PASSWORD('123456') where User='root'; flush privileges;" -uroot
  - mysql -uroot -p123456 < testsql/unielwin_course.sql
  - mysql -uroot -p123456 < testsql/unielwin_prof.sql
  - mysql -uroot -p123456 < testsql/unielwin_RA.sql
  - mysql -uroot -p123456 < testsql/unielwin_registration.sql
  - mysql -uroot -p123456 < testsql/unielwin_student.sql
script: 
  - cd jar
  - java -jar RunBB
after_script:
  - ls
  - mysql -e "show databases;" -uroot -p123456
